name = "PBaB"
uuid = "8b94e1b2-9285-41f7-a5a4-4671ab49d6bf"
authors = ["tomas votroubek <tomas.votroubek@outlook.com>"]
version = "0.1.4"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
